### ISSUE TITLE
Typo storage.googleapis.com/kubernetes-release URL

### ISSUE THREAD

**Issue by levmichael3** [johscheuer/theforeman-coreos-kubernetes#6]
Hello,
There are minor typos, with duble '<<' marks:

https://github.com/johscheuer/theforeman-coreos-kubernetes/blob/94f49b2f0dd59e0b95dcca5d1bbbfc662a5b64bf/kubernetes/standalone_cloudconfig.erb#L88

https://github.com/johscheuer/theforeman-coreos-kubernetes/blob/94f49b2f0dd59e0b95dcca5d1bbbfc662a5b64bf/kubernetes/standalone_cloudconfig.erb#L116

https://github.com/johscheuer/theforeman-coreos-kubernetes/blob/94f49b2f0dd59e0b95dcca5d1bbbfc662a5b64bf/kubernetes/standalone_cloudconfig.erb#L166

https://github.com/johscheuer/theforeman-coreos-kubernetes/blob/94f49b2f0dd59e0b95dcca5d1bbbfc662a5b64bf/kubernetes/master_cloudconfig.erb#L88

https://github.com/johscheuer/theforeman-coreos-kubernetes/blob/94f49b2f0dd59e0b95dcca5d1bbbfc662a5b64bf/kubernetes/master_cloudconfig.erb#L116

https://github.com/johscheuer/theforeman-coreos-kubernetes/blob/94f49b2f0dd59e0b95dcca5d1bbbfc662a5b64bf/kubernetes/master_cloudconfig.erb#L163

**Comment by johscheuer** [comment]
Thank you very much!  :+1:

**Comment by levmichael3** [comment]
Cheers.
I'm trying to make it work on my Foreman by the way. Can't make it work yet, might be due to tabs and spaces.

**Comment by johscheuer** [comment]
You are right there was a mistake with a tab I fixed this issue in the latest commit. Sorry for that! I also added https://coreos.com/validate which is a handy tool to check your cloud-init.

**Comment by levmichael3** [comment]
@johscheuer : **Thanks**! I've just found out about it and it really helps!
Have you succeeded using it with the wrapper Foreman provision?
