### ISSUE TITLE
wupiao parameter bug

### ISSUE THREAD

**Issue by TheKangaroo** [johscheuer/theforeman-coreos-kubernetes#7]
Hi,

i think there is a little mistake in standalone:
https://github.com/johscheuer/theforeman-coreos-kubernetes/blob/master/kubernetes/standalone_cloudconfig.erb#L149 
and 
https://github.com/johscheuer/theforeman-coreos-kubernetes/blob/master/kubernetes/standalone_cloudconfig.erb#L168 
since you use the wupiao with two parameters instead of just one.
Changing 127.0.0.1 8080 to 127.0.0.1:8080 solved this for me.

Anyway you really helped me setting up kubernetes with foreman.
Thank you!

**Comment by johscheuer** [comment]
Thanks!

I'm glad I could help you :)
