### ISSUE TITLE
README "k8s_master" should not include http tag

### ISSUE THREAD

**Issue by JohnCoconut** [johscheuer/theforeman-coreos-kubernetes#8]
In README.md, 

`k8s_master: The Kubernetes master e.g. http://172.24.1.148.`

however, in `minion_cloudconfig.erb`

`initial-cluster: master=http://<%= @host.params['k8s_master'] %>:2380`

This combination will generate a template like this,

`initial-cluster: master=http:// http://172.24.1.148`

**Comment by johscheuer** [comment]
@mywtfmp3 thanks for reporting this issue I will fix the documentation. I probably changed this with etcd2 and forgot to adjust the docs :)

**Comment by johscheuer** [comment]
If you still have any issues running it please feel free to ask :)

**Comment by JohnCoconut** [comment]
@johscheuer  Thanks for fixing it.:) I haven't been able to get cluster running with templates. But it's a very good start for me. Once I figure out the issues, I will report back.
